---
title: Illustration of variational Gaussian approximation for Poisson-normal model with one unknown
author: Peter Carbonetto
output: workflowr::wflow_html
---

*Add text here.*

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center",dpi = 120)
```

```{r}
source("../code/vgapois.R")
set.seed(1)
```

Simulate data
-------------

```{r}
n  <- 10
b0 <- -1
b  <- 1.5
x  <- rnorm(n)
r  <- exp(b0 + x*b)
y  <- rpois(n,r)
```

Compute importance sampling estimate of marginal likelihood
-----------------------------------------------------------

```{r}
s0 <- 3
ns <- 1e5
b  <- rnorm(ns,sd = sqrt(s0))
w  <- rep(0,ns)
for (i in 1:ns)
  w[i] <- compute_loglik_pois(x,y,b0,b[i])
a <- max(w)
lnZ <- log(mean(exp(w - a))) + a
```

Fit variational approximation
-----------------------------

```{r}
fit <- vgapois1(x,y,b0,s0)
mu  <- fit$par["mu"]
s   <- fit$par["s"]
print(compute_elbo_vgapois1(x,y,b0,s0,mu,s),digits = 6)
```

Compare exact and approximate posterior distributions
-----------------------------------------------------

```{r, fig.height=3, fig.width=3}
b    <- seq(-1,3,length.out = 1000)
n    <- length(b)
logp <- rep(0,n)
qb   <- dnorm(b,mu,sqrt(s))
for (i in 1:n)
  logp[i] <- compute_logp_pois(x,y,b0,b[i],s0)
maxlp <- max(logp)
plot(b,exp(logp - maxlp),type = "l",lwd = 2,col = "dodgerblue",
     xlab = "b",ylab = "relative posterior")
lines(b,qb/max(qb),col = "magenta",lwd = 2)
```
